# Generated by Django 5.1.1 on 2024-09-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image_auto', models.BooleanField()),
                ('image_bus', models.BooleanField()),
                ('price', models.CharField(max_length=100)),
            ],
        ),
    ]
