# Generated by Django 5.1.1 on 2024-09-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.CharField(max_length=150)),
                ('wheel_size', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('trac', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Wash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type', models.CharField(max_length=100)),
                ('instructions', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Block',
        ),
    ]
