# Generated by Django 5.1.1 on 2024-10-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
